site_name: IE科协
site_description: IE科协技术资料
site_author: IE科协
site_url: https://ie.rtfd.io
copyright: Do not distribute.

theme:
  name: mkdocs
  highlightjs: true
  hljs_style: lightfair
  mathjax: true
  navigation_depth: 3
  custom_dir: custom/

nav:
  - 首页: index.md
  - PyTorch:
    - 安装: pytorch/install.md
    - 基础知识: pytorch/basics.md
    - 图像数据建模：CNN: pytorch/cnn.md
    - 序列数据建模：RNN: pytorch/rnn.md
    - 向量数据建模：MLP: pytorch/mlp.md
  - TensorFlow2:
    - 安装: tensorflow2/getting-started.md
    - 基础知识: tensorflow2/basics.md
  - 工作手册:
    - 编辑页面: manual/edit.md
    - 发布更新: manual/upd.md

plugins: []
